package jpql;

import java.util.List;

import javax.persistence.EntityManager;
//import javax.persistence.Query;
import javax.persistence.TypedQuery;

import dao.JPAUtil;
import entities.Product;

public class ProductJPQL {
	static EntityManager em;
	static
	{
		em=JPAUtil.getEntityManager();
	}
	
	public static List<Product> getProductsByQuantity(int quantity)
	{
//		List<Product> plist;
//		Query query=em.createQuery("SELECT product from Product product",Product.class);
//		plist=query.getResultList();
//		return plist;
		
		String qStr="SELECT product FROM Product product WHERE product.quantity >=pqty";
		TypedQuery<Product> tquery = em.createQuery(qStr, Product.class);
		tquery.setParameter("pqty",quantity);
		return tquery.getResultList();
	}
}

//About ResultSet
//A ResultSet object is a table of data representing a database result set, 
//which is usually generated by executing a statement that queries the database.
//The object of ResultSet maintains a cursor pointing to a row of a table.

//Return value

//This method returns a boolean value specifying whether the ResultSet object contains more rows. 
//If there are no rows next to its current position this method returns false, else it returns true.


//Interface ResultList. 
//A JavaBean interface that represents an aggregation of the Job's known Results, 
//collected from each completed Batch. Returns the array of items ids contained in the batch. 
//Returns the array of file paths from which the items are derived.